blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://github.com/programinglive/commiter/security/policy
    about: Please read our security policy before reporting vulnerabilities.
